[build-system]
build-backend = 'mesonpy'
requires = ['meson-python']

[project]
name = 'DBzero'
version = '0.1.0'
description = 'DBZero Community edition'
readme = 'README.md'
requires-python = '>=3.11'
license = {file = 'LICENSE.txt'}
authors = [
]
dependencies = [
    'fasteners==0.19'
]

[tool.semantic_release.remote]
password = { env = "GH_TOKEN" }

[tool.pytest.ini_options]
testpaths = ["python_tests"]