name: Call Private Workflow

on:
  workflow_dispatch:

permissions:
  contents: read   # allows reading private repos in the same org

jobs:
  call_private_workflow:
    uses: dbzero-software/dbzero-benchmarks/.github/workflows/private-workflow.yml@main
    with:
      input_message: "Hello from public repo"
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}